version: '3.4'

services:
  bluewhale.security:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AudienceUrl=http://${BLUEWHALE_ADDRESS}:5101
    ports: 
      - "5100:80"

  bluewhale.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Security.Url=http://10.0.75.1:5100
    ports: 
      - "5101:80"