version: '3.4'

services:
  bluewhale.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "5002:80"
    networks:
      default:
        ipv4_address: 172.19.157.179

  bluewhale.security:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "5100:80"
    networks:
      default:
        ipv4_address: 172.19.157.178

networks:
  default:
    external:
      name: nat