version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: bluewhale.sql
    volumes:
      - "c:/BlueWhale.UsersData:/var/opt/mssql"

  bluewhale.security:
    image: ${DOCKER_REGISTRY}bluewhalesecurity
    container_name: bluewhale.security
    depends_on:
      - sql.data
    build:
      context: .
      dockerfile: BlueWhale.Security/Dockerfile

  bluewhale.exchange:
    image: ${DOCKER_REGISTRY}bluewhaleexchange
    container_name: bluewhale.exchange
    depends_on:
      - bluewhale.security
    build:
      context: .
      dockerfile: BlueWhale.Exchange/Dockerfile

  bluewhale.main:
      image: ${DOCKER_REGISTRY}bluewhalemain
      container_name: bluewhale.main
      depends_on:
        - bluewhale.security
      build:
        context: .
        dockerfile: BlueWhale.Main/Dockerfile