version: '3.4'

services:
  bluewhale.security:
    image: ${DOCKER_REGISTRY}bluewhalesecurity
    build:
      context: .
      dockerfile: BlueWhale.Security\Dockerfile

  bluewhale.main:
      image: ${DOCKER_REGISTRY}bluewhalemain
      build:
        context: .
        dockerfile: BlueWhale.Main\Dockerfile
      depends_on:
        - bluewhale.security