version: '3.4'

services:
  bluewhale.security:
    image: ${DOCKER_REGISTRY}bluewhalesecurity
    container_name: bluewhale.security
    build:
      context: .
      dockerfile: BlueWhale.Security/Dockerfile

  bluewhale.main:
      image: ${DOCKER_REGISTRY}bluewhalemain
      container_name: bluewhale.main
      depends_on:
        - bluewhale.security
      build:
        context: .
        dockerfile: BlueWhale.Main/Dockerfile