version: '3.4'

services:
  bluewhale.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  bluewhale.security:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

networks:
  default:
    external:
      name: nat

